# default config file that property value can be override by current NODE_ENV config file
server:
  port: 3000
  appName: Business API Middleware

system:
  useForever: false
  nodeProcessNumber: 1

log:
  path: logs/

targets:
  appApi:
    baseUrl: http://localhost:3000

